class Strings {
  static Map<String, Map<String, String>> translationsKeys = {
    "en": {
      "no_internet": "No internet Connection",
      "GRIEVANCE_PORTAL": "GRIEVANCE PORTAL",
      "Dashboard": "Dashboard",
      "Home": "Home",
      "About": "About",
      "Welcome_to_Grievance": "Welcome to Grievance Readdress Portal",
      "Please_click_on_the_below_buttons":
          "Please click on the below buttons to post/track grievance.",
      "Post_Grievance": "Post Grievance",
      "Track_Grievance": "Track Grievance",
      "Total_Grievance": "Total Grievance",
      "Name": "Name",
      "Enter_here": "Enter here",
      "Department": "Department",
      "Select": "- Select -",
      "Address": "Address",
      "enter_your_address": "Enter your Address",
      "Grievance_Details": "Grievance Details",
      "Message": "Message…",
      "Submit": "Submit",
      "Back": "Back",
      "Log_In": "Log In",
      "Phone_Number": "Phone Number",
      "Verified": "Verified",
      "You_have_successfully_verified_the":
          "You have successfully verified the",
      "Verify_your_Mobile_Number":
          "Verify your Mobile Number and post your grievance.*",
      "Go_to_Dashboard": "Go to Dashboard",
      "Send_Inquiry": "Send Inquiry",
      "Thank_You": "Thank You",
      "Submitting_your_grievances":
          "Submitting your grievances. We will get back to you as soon as possible.",
      "Grievance_List": "Grievance List",
      "Grievance_History": "Grievance History",
      "Status": "Status",
      "Date_Created": "Date Created",
      "Remark": "Remark",
      "Email_History": "Messages History",
      "From_Admin_to_You": "From Admin to You",
      "From_You_to_Admin": "From You to Admin",
      "Subject": "Subject",
      "Enter_your_subject": "Enter Your Subject",
      "Enter_your_message": "Enter Your Message",
      "Message_field": "Message",
      "Grievence_Details": "Grievence Details",
      "Request_Id": "Request Id",
      "Customer_Name": "Customer Name",
      "Description": "Description",
      "Send": "Send",
      "Close": "Close",
      "Failed": "Failed",
      "enter_proper_message": "Enter proper message",
      "enter_proper_subject": "Enter proper subject",
      "Message_sent_successfully": "Message sent successfully",
      "Log_out": "Log Out",
      "AreYouSureYouWantToLogOut": "Are you sure want to Log Out ?",
      "Image": "Image",
      "Send_Message": "Send Message",
      "Select_GPWard": "GP/Ward",
      "Select_Village": "Village",
      "Please_enter_reopen_reason": "Please Enter Reopen Reason",
      "Send_us_your_feedback": "Send Us Your Feedback",
      "are_you_satisfied": "Are you satisfied with our work?",
      "please_enter_your_feedback": "Please enter your feedback",
      "please_enter_proper_number": "Please enter proper number",
      "please_enter_name": "Please enter Name",
      "please_enter_grievance_detail": "Please enter Grievance Details",
      "new_message": "New Message",
      "my_profile": "My Profile",
      "first_name": "First Name",
      "last_name": "Last Name",
      "email": "Email",
      "mobile_no": "Mobile No",
      "cannot_be_edited": "Cannot be edited",
      "please_enter_first_name": "Please enter First Name",
      "please_enter_last_name": "Please enter Last Name",
      "please_enter_address": "Please enter address",
      "refresh": "Refresh",
      "your_feedback": "Your Feedback"
    },
    "or": {
      "no_internet": "କ internet ଣସି ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ନାହିଁ |",
      "GRIEVANCE_PORTAL": "ଗ୍ରାଇଭାନ୍ସ ପୋର୍ଟାଲ୍ |",
      "Dashboard": "ଡ୍ୟାସବୋର୍ଡ |"
    }
  };
}
